name: Test code
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          cp src/config.def.h src/config.h
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: platformio run